name: Create PR on New Branch

on:
  create:
    branches:
      - '*'

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automatically created PR for new branch"
          branch: ${{ github.ref }}
          base: 'main'

#
