name: Dump

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dump_variables:
    runs-on: ubuntu-latest

    steps:
      - name: Dump Variables
        run: |
          echo "Dumping Variables"
          env | sort
#
